apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ckqxh803c-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-56d258bbe0.su0l.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:b12ecc15855f5218df730b7889fa047e0069e255@sha256:9e243c25cd6d4ed24187b11e04a054e41f176d62e2fbe065cb4dce97d4ddfe59
          name: container-image
